apiVersion: v1
kind: Pod
metadata:
  name: ubu-debug
  labels:
    app: ubu-debug
spec:
  containers:
  - image: dnlloyd/ubu-debug
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubu-debug
  restartPolicy: Always
