apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dev.fhcdan.net
  labels:
    app: web-skp
  name: web-skp
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: web-skp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-skp
  name: web-skp
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-skp
  template:
    metadata:
      labels:
        app: web-skp
    spec:
      containers:
      - image: 458891109543.dkr.ecr.us-east-1.amazonaws.com/web-skp:0.6.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: web-skp
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: null
        securityContext: null
      imagePullSecrets:
      - name: regcred
      securityContext: null
      serviceAccountName: default
