---
# Source: terraform-cloud-operator/templates/clusterrole.yaml
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: fhc-dan-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - agentpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
---
# Source: terraform-cloud-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fhc-dan-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
# Source: terraform-cloud-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fhc-dan-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
---
# Source: terraform-cloud-operator/templates/clusterrolebinding.yaml
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fhc-dan-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fhc-dan-manager-role
subjects:
- kind: ServiceAccount
  name: fhc-dan-controller-manager
  namespace: tfc-operator-system
---
# Source: terraform-cloud-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fhc-dan-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fhc-dan-proxy-role
subjects:
- kind: ServiceAccount
  name: fhc-dan-controller-manager
  namespace: tfc-operator-system
---
# Source: terraform-cloud-operator/templates/role.yaml
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fhc-dan-leader-election-role
  namespace: tfc-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
# Source: terraform-cloud-operator/templates/rolebinding.yaml
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fhc-dan-leader-election-rolebinding
  namespace: tfc-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fhc-dan-leader-election-role
subjects:
- kind: ServiceAccount
  name: fhc-dan-controller-manager
  namespace: tfc-operator-system
