apiVersion: v1
kind: Namespace
metadata:
  name: tfc-operator-system
---
# Source: terraform-cloud-operator/templates/serviceaccount.yaml
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fhc-dan-controller-manager
  namespace: tfc-operator-system
