apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-skp
spec:
  template:
    spec:
      containers:
        - name: web-skp
          image: "458891109543.dkr.ecr.us-east-1.amazonaws.com/web-skp:0.6.0"
