---
# Source: prometheus/templates/server/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus-18
    chart: prometheus-18.0.0
    heritage: Helm
  name: prometheus-18-server
subjects:
  - kind: ServiceAccount
    name: prometheus-18-server
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-18-server
