apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-auth
spec:
  template:
    spec:
      containers:
        - name: flask-auth
          image: "458891109543.dkr.ecr.us-east-1.amazonaws.com/flask-auth:0.1.0"
