apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- git@github.com:dnlloyd/web-skp.git/deploy/bases?=main

namespace: dev

patchesStrategicMerge:
- service.yaml
- deployment.yaml
