---
# Source: prometheus/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus-18
    chart: prometheus-18.0.0
    heritage: Helm
  name: prometheus-18-server
  namespace: default
  annotations:
    {}
