---
# Source: prometheus/templates/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus-18
    chart: prometheus-18.0.0
    heritage: Helm
  name: prometheus-18-server
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    component: "server"
    app: prometheus
    release: prometheus-18
  sessionAffinity: None
  type: "ClusterIP"
