apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-web-skp
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/kustomize/separate-repos/deployments/overlays/modules/dev/web-skp
    repoURL: https://github.com/dnlloyd/my-k8s
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=false