apiVersion: apps/v1
kind: Deployment
metadata:
  name: skp
  namespace: www
spec:
  selector:
    matchLabels:
      app: skp
  replicas: 4
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skp
    spec:
      containers:
      - image: 458891109543.dkr.ecr.us-east-1.amazonaws.com/web-skp:0.4.1
        name: web-skp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      imagePullSecrets:
        - name: regcred
