apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: dan
spec:
  request: xxx
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 604800  # one week
  usages:
  - client auth