kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: www
  name: read-only
rules:
- apiGroups: [“”] # “” indicates the core API group
  resources: [“pods”, "services"]
  verbs: [“get”, “watch”, “list”]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-dnlloyd
  namespace: www
subjects:
- kind: Group
  name: read-only
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io
