apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: # TODO: move to git ref
- ../../../../../platform/bases/clogd

namespace: dev

patchesStrategicMerge:
- service.yaml
- deployment.yaml