apiVersion: v1
kind: Service
metadata:
  name: memes
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: memes.fhcdan.net
  namespace: www
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: memes
