apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-config
  namespace: dev
data:
  newrelic.ini: |
    [newrelic]
    app_name = flask-auth
    distributed_tracing.enabled = true
    monitor_mode = true
    log_level = info
    ssl = true
    high_security = false
    transaction_tracer.enabled = true
    transaction_tracer.transaction_threshold = apdex_f
    transaction_tracer.record_sql = obfuscated
    transaction_tracer.stack_trace_threshold = 0.5
    transaction_tracer.explain_enabled = true
    transaction_tracer.explain_threshold = 0.5
    transaction_tracer.function_trace =
    error_collector.enabled = true
    error_collector.ignore_errors =
    browser_monitoring.auto_instrument = true
    thread_profiler.enabled = true
    [newrelic:development]
    monitor_mode = false
    [newrelic:test]
    monitor_mode = false
    [newrelic:staging]
    app_name = flask-auth (Staging)
    monitor_mode = true
    [newrelic:production]
    monitor_mode = true