apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../bases

namespace: dev

patchesStrategicMerge:
- service.yaml
- deployment.yaml

# until you can get kubectl ksops working
# generators:
# - new-relic-secret-generator.yaml

# until you can get kubectl ksops working
resources:
- ../../../deploy-secrets/new-relic-secret.yaml

configMapGenerator:
- name: newrelic-config
  files:
  - newrelic.ini
