apiVersion: v2
appVersion: v0.24.0
description: The Alertmanager handles alerts sent by client applications such as the
  Prometheus server.
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
maintainers:
- email: monotek23@gmail.com
  name: monotek
- email: naseem@transit.app
  name: naseemkullah
name: alertmanager
sources:
- https://github.com/prometheus/alertmanager
type: application
version: 0.22.0
