apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: skp
  namespace: www
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skp-deployment
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
