apiVersion: v1
kind: Service
metadata:
  name: flask-auth
  labels:
    app: flask-auth
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flask-auth
