apiVersion: apps/v1
kind: Deployment
metadata:
  name: memes
  namespace: www
spec:
  selector:
    matchLabels:
      app: memes
  replicas: 2
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: memes
    spec:
      containers:
      - image: dnlloyd/web-fam-meme:latest
        name: web-fam-meme
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      # imagePullSecrets:
      #   - name: regcred-docker
