apiVersion: v1
kind: Service
metadata:
  name: web-skp
  labels:
    app: web-skp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web-skp
