---
# Source: prometheus/charts/prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-18-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    chart: prometheus-pushgateway-1.21.0
    heritage: Helm
    release: prometheus-18
