name: ASP.NET core Docker image build and push to ECR
on:
  push:
    branches: [ master ]
    paths:
      - 'docker/aspnet-core/**'
      - '.github/workflows/build-aspnet-core.yml'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_EcrAdmin }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EcrAdmin }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: aspnet-core
        IMAGE_TAG: '0.1.0'
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./docker/aspnet-core
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
