name: Ubuntu debug image Docker image build and push to DockerHub
on:
  push:
    branches: [ master ]
    paths:
      - 'docker/ubu-debug/**'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action
    #   with:
    #     images: dnlloyd/ubu-debug
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: dnlloyd/ubu-debug:latest
